version: '2'
services:
    yepps-app:
        image: yepps
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@yepps-oracle:1521:yepps
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8111:8111
